### ISSUE TITLE
Plotting more than 1 yaml file in phonopy-bandplot only possible with legacy

### ISSUE THREAD

**Issue by manie204** [atztogo/phonopy#105]
Hi Togo,

I noticed that in the phonopy-bandplot script, the function ```plot``` does not iterate over ```filenames```, unkile in the "legacy" version, ```old_plot```. This causes only the first file to be plotted.

**Comment by atztogo** [comment]
It is true. Do you want?

**Comment by manie204** [comment]
I can work around it, no problem. I just thought that I better report it since neither the online documentation nor ```--help``` say anything about that.

**Comment by atztogo** [comment]
Thanks for your report. I will have a look at if I can make it possible. If not easy, I will write this issue on the documentation.

**Comment by manie204** [comment]
Thanks :)

**Comment by atztogo** [comment]
Do you assume the band structures are plotted in the same Brillouin zone? I am considering if we should support the case calculating band structures for the same compound with changing pressure (or unit cell volume), which requires some more efforts to implement.

**Comment by manie204** [comment]
I assume that they are in the same Brillouin zone and use the same q-path, yes. I'm not sure that the extra effort would be worth it but it could be a nice feature for sure. Do you imagine lining up the high-symmetry points in the plot if the cell geometry is slightly different?

**Comment by atztogo** [comment]
Yes, having more features is nice, but up to effort worth enough.

> Do you imagine lining up the high-symmetry points in the plot if the cell geometry is slightly different?

No. What I consider is to keep the same distance unit, i.e., the special points will be located at different points in the plot.

In any case, some check is necessary in which conditions several band.yaml data can be plotted together. Anyway, this stuff is better to consider in trial and error by writing the code.

**Comment by atztogo** [comment]
I made a tentative implementation at bandplot branch, https://github.com/atztogo/phonopy/tree/bandplot. Only works when the same Brillouin zone and the same q-path.

**Comment by manie204** [comment]
Great! Thanks for the quick fix.

**Comment by atztogo** [comment]
I merged the bandplot branch into the develop branch. I will close this issue. Please reopen any time when you need.
