### ISSUE TITLE
Error in phonopy-FHI-aims

### ISSUE THREAD

**Issue by shahramyalameha** [atztogo/phonopy#111]
Dear all,
I get the following error while executing: 
================================================
# post-processing free energy
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/home/shahram/phonopy-FHI-aims", line 978, in <module>
    frequency_unit_to_THz , do_matplotlib=do_matplotlib)
  File "/home/shahram/phonopy-FHI-aims", line 513, in post_process_free_energy
    weights=mesh_obj.get_weights())
TypeError: __init__() got an unexpected keyword argument 'weights'
=======================================================
help me.

**Comment by atztogo** [comment]
phonopy-FHI-aims is no more supported by phonopy.
If you want to know the support on aims, please have a look at this post, https://sourceforge.net/p/phonopy/mailman/phonopy-users/thread/3088753.K2aOG8Kqs6%40theobook135/#msg36911099

If you have more questions, please send your question to the FHI-aimls community or phonopy mailing list.

I will close this issue.
