### ISSUE TITLE
Mutable values in defaults

### ISSUE THREAD

**Issue by jochym** [atztogo/phonopy#13]
I have used quantified code automatic style check on my repositories. It has found some issues with the code. Some are minor or not important but some are potentially quite serious. I will try to correct
these issues or accept their automatic fix into my tree. I am starting with the following issue: you should never use mutable data as a default value of the argument of the function.
This is potentially dangerous - if the mutable default value is changed inside the function the default will change for every subsequent call to the function and if it is returned and used it will influence every place it is used in the code. It is often a source for obscure and difficult to trace errors. The important feature here is that the defaults are *not* generated when the function is called but when they are *defined*. I do not know if you want this corrections as pull requests, diffs or some other form. This particular fix is commit 0b952cbd60b1b1d1b2ac32eb19a0fd99bf90caeb - you can cherry-pick it from my tree or I will generate pull request (tell me against which branch you want it).

**Comment by atztogo** [comment]
Simply I didn't know this. Yes, it's dangerous. Thanks for telling this. I want to accept your corrections as pull requests to merge to develop branch. But if it's easier for you that I will cherry-pick them, I will do it so. Just please tell me. I have many things to learn from you...

**Comment by jochym** [comment]
Ok. I will be making pull requests then. I guess you would prefer them to be against develop branch? I am actively tracking master for the packaging and I was making patches against that branch. I will switch to develop for the patches.

**Comment by atztogo** [comment]
Yes. I prefer develop branch for merging your commit at this moment. But I'm afraid of that this is due to my lack of knowledge on how to use git well.
