### ISSUE TITLE
Crash in phonopy-qha (1.11.2)

### ISSUE THREAD

**Issue by beeck** [atztogo/phonopy#22]
Hi Togo,
sometimes a crash can occur with phonopy-qha due to a cv of 0.
This can be fixed (hopefully) with the attached patch file. The error must be catched and treated, but then I dont know if a gamma of Zero is bad or not. Have a look at the patch...

[phonopy-1.11.2_iac_rwth.zip](https://github.com/atztogo/phonopy/files/458750/phonopy-1.11.2_iac_rwth.zip)

**Comment by atztogo** [comment]
Hi beeck,

Thanks. I applied your patch, 59f9dfd2630e10d8023fc3722f2ff0c3787e8714. I think gamma = 0 is a good choice.
