### ISSUE TITLE
t_max in QHA calculations via Python API

### ISSUE THREAD

**Issue by bocklund** [atztogo/phonopy#27]
Hi,

As a user via the Python API for a QHA calculation, I want to create a `Phonopy` object and then call the `set_thermal_properties` method with, for example, a `t_max=1000` and `t_step=10`. When I then call the `get_thermal_properties` method, the last 4 temperatures are truncated and I am left with `T=[0, 10, ..., 950, 960]` where I would expect the list to go to 1000. 

I assume I am using the code correctly (if not, please advise) and the truncation is done as a side effect of the calculation, but I think it would be more reasonable to extend the temperature range automatically within Phonopy in order to return the temperature range that I, the user, expect when I pass in `t_max` as a parameter.

**Comment by atztogo** [comment]
Do you mean about the usage of Phonopy class? If so, it is something wrong. It should not be truncated. But PhonopyQHA may truncate depending on the range of input data.

**Comment by bocklund** [comment]
We are using an instance of a Phonopy class to get the thermodynamic data for each structure in a set of structures in a QHA calculation and then passing the calculated energies, heat capacities and entropies to PhonopyQHA, which truncates as you said. Is there a more correct way to do this without truncation?

**Comment by atztogo** [comment]
Numerical differentiation up to second order is done in PhonopyQHA, so it needs more temperature points than the tmax. So you need to input thermal_properties obtained by Phonopy which have at least extra 4 temperature points, i.e., Phonopy.set_thermal_properties with larger tmax is necessary than the tmax for PhonopyQHA. It's tricky and not documented well.

**Comment by bocklund** [comment]
So since we are going through using the Phonopy class first, there doesn't appear to be a straightforward way to do this other than extend the t_max range by 4 elements 'by hand', correct?

**Comment by atztogo** [comment]
Yes, I think so.

I understand that the problem is that PhonopyQHA is not well designed. Maybe it is better to prepare another QHA API that wraps Phonopy and current PhonopyQHA. PhonopyQHA is getting old and  slowly dying. Now is the good timing to improve it if I can have time to do it...

**Comment by jochym** [comment]
Let me add my penny to the discussion. Maybe this can be solved at the level of documentation. t_max is the highest temperature *used* in the calculation. Silently extending the range may be not so good idea in many pathological cases (e.g. systems with structural phase transition). I, personally would prefer to have it work like it is working now and have this feature clearly marked in the docstring and manual.

**Comment by atztogo** [comment]
I agree with @jochym. At least I will keep PhonopyQHA code as it is and hopefully documentation will be written for it.
To make thermal expansion calculation under QHA more clever is also my direction to do. This will be done by calling PhonopyQHA, so PhonopyQHA will not be modified.
