### ISSUE TITLE
Windows incompatibility

### ISSUE THREAD

**Issue by jochym** [atztogo/phonopy#30]
Unfortunately there is a problem with all windows builds. Similar to spglib. Would you take a look at [these builds](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.9286) @atztogo ? Maybe the problem is not very fundamental? I have no knowledge about writing extensions so I really cannot do anything about it. For now I will block windows builds and limit packages to linux/osx.

**Comment by jochym** [comment]
At least one problem is a fact that M_PI is undefined in visual studio by default. 
It is only used in two places: [c/harmonic/derivative_dynmat.c](https://github.com/atztogo/phonopy/blob/0735d3e9ef9cf84d3f57e2503dedd1c83b86dd65/c/harmonic/derivative_dynmat.c)  and [harmonic/dynmat.c](https://github.com/atztogo/phonopy/blob/0735d3e9ef9cf84d3f57e2503dedd1c83b86dd65/c/harmonic/dynmat.c) . Maybe we should just drop this and use our own definition of Pi?

**Comment by atztogo** [comment]
I have a look at the builds, and saw strange errors happened for python 2.7 and 3.4 but not for python 3.5. For this I have no idea at this moment.
I have done replacing M_PI by #define PI 3.14159265358979323846. This is made for the develop branch.

**Comment by atztogo** [comment]
I guess older visual studios require old C style than C90. If it is true and needed, I will consider to work for it, since probably it affects only _phonopy.c and _spglib.c. I mean, in the main source codes, I think I wrote in an old C style. So I hope it is not so hard job.

**Comment by jochym** [comment]
The new visual studio is c99 compliant by default (gcc is not, you need to add -std=c99 to switch standard -mode). These constants are no longer part of the standard library. I am not sure I understand the py27 and py34 case. The py35 is easy and your fix should probably make it compile. 

I have also noticed large differences between versions of visual studio in different environments. For py27 it is VC9.0 for py34 - VC10.0 and for py35 it is VC14.0. This may be the reason for different behaviour. I will rise the issue with conda-forge creators.

**Comment by jochym** [comment]
I have fond the answer:
http://stackoverflow.com/questions/24966785/compiling-python-extensions-with-different-visual-studio-version

Unfortunately on windows you need to keep the whole toolchain in sync with python binary. Some professional development platform (IMHO)! Probably you are using a bit too modern C in your extensions. Is the code in _phonopy.c (l. 172...) auto-generated or hand written? Or maybe it is some kind of template? Sometimes it may be quite trivial to accommodate older versions of standard, sometimes not so trivial OTOH. Let me know if I can help. I am fairly decent C programmer, I am just not familiar with python extensions.

**Comment by atztogo** [comment]
To see how I understand it correctly, I updated _spglib.c in the atztogo/spglib develop branch to accept old-style-definiton. My compilation test was done with gcc with the following options,

export CFLAGS="-Wall -Wextra -std=c89 -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition"

but not on visual studio that I don't have.

Can I ask you to build python-spglib of my atztogo/spglib develop branch on your appVeyor system and see how it goes? If this change works, it means my job is trivial. So if spglib-python build seems OK, I will move to _phonopy.c.

**Comment by jochym** [comment]
I cannot be quite sure because there are some issues with build matrix on appVeyor but the py27 build worked and tested itself fine. I will let you know as soon as I get other tests results. And it did not broke other builds. I am hopeful. But is it kind of regression in the code style?

**Comment by atztogo** [comment]
Thanks!
In the old C style, variable declarations have to be placed at the beginning of the block. This is all what I did in the _spglib.c update. In C99, array size is dynamically allocated with its array declaration, which is very useful. But I found I didn't use this feature of C99 in _spglib.c. So overall, the changes I made for _spglib.c were trivial, just there were many lines I needed to change.

If the behaviour of the build for py27 altered by my change, probably the direction we are going is correct.

**Comment by jochym** [comment]
It is changed alright ;) It builds properly ([Build list](https://ci.appveyor.com/project/conda-forge/spglib-feedstock/build/1.0.10)) - there is just a substantial number of warnings concerning use of strcpy - which is admittedly a slightly unsafe function - maybe you should consider using strcpy_s instead as advised. But this is a minor issue. Otherwise the compilation is clean and the tests run without a problem. I think we are on the path to having all three platforms supported!

**Comment by atztogo** [comment]
Great! In the similar manner, I have updated _phonopy.c in the atztogo/phonopy master/rc/develop branch.
I will replace strcpy with strcpy_s in spglib someday soon.

**Comment by jochym** [comment]
OK. I'll try to integrate your changes into the package today late evening. Expect some report next morning... hopefully

**Comment by jochym** [comment]
I have managed to test spglib on all platforms. All is fine. It builds
everywhere. I think you may adapt phonopy as well.

P.

**Comment by atztogo** [comment]
I see. Thanks.

**Comment by jochym** [comment]
There is a problem on windows with test_get_commensurate_points (harmonic.test_dynmat_to_fc.TestDynmatToFc).
See here:
https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.9364/job/jege1ro8f6m7ilu0

Apparently sometimes periodicity does not kick-in properly

**Comment by atztogo** [comment]
Thanks. I fixed it in atztogo/phonopy develop branch.

**Comment by jochym** [comment]
And it worked for phonopy as well. The package is submitted for inclusion now. Please merge your last changes into master.

**Comment by atztogo** [comment]
I have merged to master the last changes.
