### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by anhph** [atztogo/phonopy#35]
Hi,

I'm getting an error "Phonopy-C extension needs to build properly" after installation of the latest phonopy version. Can you help ?

Thanks,
Anh

**Comment by atztogo** [comment]
I can't help since lack of information.

**Comment by atztogo** [comment]
And please send this issue to the mailing list, https://lists.sourceforge.net/lists/listinfo/phonopy-users .

**Comment by atztogo** [comment]
I close this issue because of no communication for long time.
