### ISSUE TITLE
Force constant unit conversion

### ISSUE THREAD

**Issue by linumalakkal** [atztogo/phonopy#37]
Hi,
I have used Phonopy with the ESPRESSO backed, and i understand that the FORCE_CONSTANTS are in Ry/au^2 but i need the force constant  to be in eV/A**2. and  the conversion factor is 0.4858682984. But when i try to do the unit conversion i am not getting any difference. 

Can you please have a look at my script and help me rectify the issue. 

the command i use is 

phonopy --pwscf -c CeO2.in  -p --factor 0.4858682984 -s  mesh.conf

my mesh.conf is

DIM=4 4 4
MP=12 12 12
GAMMA_CENTER=.TRUE.
FORCE_CONSTANTS=Write

Thank you for your help 

regards
Linu 
Graduate student 
University of Saskatchewan

**Comment by atztogo** [comment]
Here in this issue on github, I would like you to ask more code specific issues. For such a general question, please send your question to the mailing list, and please don't send e-mails to me directly.

There is no easy interface to do it. But the format of FORCE_CONSTANTS (force_constants.hdf5) is quite easy. You can do it by yourself by writing some short script.

**Comment by atztogo** [comment]
I will close this issue because of no communication for long time.
