### ISSUE TITLE
`get_equivalent_smallest_vectors` is slow

### ISSUE THREAD

**Issue by ExpHP** [atztogo/phonopy#40]
When computing eigenvectors for twisted bilayer graphene, I find that phonopy spends an extremely long amount of time at startup in a function called `get_equivalent_smallest_vectors`.  With `--readfc --hdf5`, this function ends up dominating the entire computation.

```
         17133219 function calls (17127871 primitive calls) in 97.987 seconds                       
                                                                                                    
   Ordered by: cumulative time                                                                      
                                                                                                    
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)                             
        1    0.000    0.000   97.987   97.987 phonopy:3(<module>)                                   
        1    0.001    0.001   97.323   97.323 phonopy:37(<module>)                                  
        1    0.000    0.000   86.540   86.540 api_phonopy.py:295(set_force_constants)               
        1    0.000    0.000   86.540   86.540 api_phonopy.py:1150(_set_dynamical_matrix)            
        1    0.000    0.000   86.540   86.540 dynamical_matrix.py:84(__init__)                      
        1    0.364    0.364   86.526   86.526 dynamical_matrix.py:396(get_smallest_vectors)         
    28224   67.834    0.002   86.079    0.003 dynamical_matrix.py:358(get_equivalent_smallest_vectors)
   762348    4.322    0.000    8.251    0.000 linalg.py:2022(norm)                                  
        1    0.000    0.000    5.774    5.774 api_phonopy.py:482(write_yaml_band_structure)         
        1    0.051    0.051    5.774    5.774 band_structure.py:126(write_yaml)                     
        3    5.427    1.809    5.615    1.872 band_structure.py:188(_get_q_segment_yaml)            
    28224    0.020    0.000    5.239    0.000 cells.py:354(get_reduced_bases)                       
    28224    0.340    0.000    5.219    0.000 cells.py:364(get_Delaunay_reduction)                  
    28224    0.531    0.000    3.828    0.000 cells.py:395(get_shortest_bases_from_extented_bases)  
  1684288    3.669    0.000    3.669    0.000 {numpy.core.multiarray.dot}                           
        1    0.000    0.000    3.652    3.652 api_phonopy.py:448(set_band_structure)                
        1    0.000    0.000    3.652    3.652 band_structure.py:58(__init__)                        
```

I've been trying out various optimization strategies for this function and am working on a PR, which I will post shortly.

**Comment by ExpHP** [comment]
[my benchmark has been posted here](https://github.com/ExpHP/phonopy-eigenvector-tblg-benchmark/tree/master)

**Comment by ExpHP** [comment]
Update: Benchmarks on the merged version look similar to the one posted above, so `sqrt(x**2.sum(axis=1))` has the same performance characteristics to linalg.norm.

Now that the benchmark is fast enough to run multiple times, we can get more useful statistics.
Over five runs on the latest version, I see (for `get_smallest_equivalent_vectors`):

* Best running time: 9.75s
* Mean running time: 10.2s +/- 0.67s

---

Do you have any thoughts on precomputing the reduced basis and matrix inverses (as I wrote about under [further possible optimizations](https://github.com/atztogo/phonopy/pull/41#issue-220304931))?

It seems that `reduced_bases` is most closely related to `supercell` (I think this is class Atoms?), so one possibility is to give Atoms a `_reduced_bases` member... however, computing the basis also depends on the symmetry precision (and Atoms currently does not, so this would feel like a hack).

Another possible solution could be to refactor the places where it is used. Currently, I see that it is used in three places, all of which are doubly-nested loops over atoms:

* [run()](https://github.com/atztogo/phonopy/blob/5db71c0a14e7d961c11b1c421e6d5d03d71cfcce/phonopy/phonon/thermal_displacement.py#L316-L342) in thermal_displacements.py
* [get_smallest_vectors()](https://github.com/atztogo/phonopy/blob/14c44158e1190868016fddf828226433abe13b3a/phonopy/harmonic/dynamical_matrix.py#L417-L426) in dynamical_matrix.py
* [rotational_invariance()](https://github.com/atztogo/phonopy/blob/2463a43700e5f3e1a3537ec77566c8cb2c720f84/phonopy/harmonic/force_constants.py#L442-L457) in force_constants.py

If the similarities between these loops could be pulled out into a single function, then it might become more obvious how to make it faster.  However, the loops look pretty different from each other right now, so I don't know if this is even possible.

**Comment by atztogo** [comment]
Thanks for your suggestions. There is no reason not precomputing it. I think it would be better stored in the Primitive class instead of the Supercell class because primitive cell is created from supercell and the most important crystal-structural information (including about supercell) is to be contained in Primitive object.

ThermalDistances class and rotational_invariance() method are not used usually. So it is not urgent to treat them by refactoring. They are written for experimental purposes and may be removed someday.

**Comment by atztogo** [comment]
Thanks. I will close this issue.
