### ISSUE TITLE
Wishlist: Binary alternative to band.yaml

### ISSUE THREAD

**Issue by ExpHP** [atztogo/phonopy#49]
YAML is a very good format for configuration, but not so good for serializing big data.  Here's how long it takes me just to call `yaml.load` on a 111 MB band.yaml file.

```python
def yaml_load_time(path):
    import time, yaml, resource

    start = time.time()
    with open(path) as f:
        yaml.load(f)
    end = time.time()

    gb = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024 / 1024

    print('time: {:.02f} seconds'.format(end - start))
    print('max memory usage: {:.02f} GiB'.format(gb))

# 111 MB file
yaml_load_time('medium-band-news-3.yaml')
```

**time:** 652.31 seconds (!!!)  
**max memory usage:** 7.02 GiB  (!!!!)

On my own fork, I've been using [a terrible hack] to optionally replace band.yaml with a number of numpy `.NPY` files.  (Obviously, this isn't what we should do in phonopy!) A more principled solution might be to **add a config option that causes Phonopy to write some `band.hdf5` file** that has datasets for frequency, eigenvectors, q-points, etc.

**Some notes:**

* Scripts like `bandplot` should also support the new format
* If this gets added, it should be a **separate option from `--hdf5`**, because I can imagine good reasons why somebody might want to use `force_constants.hdf5` but also have a readible band.yaml file. (also, it would break many things that currently use `--hdf5`)
  - idea: `--band-format=hdf5`. (default being `--band-format=yaml`)

[a terrible hack]: https://github.com/ExpHP/phonopy/blob/5e1b1187a76e14e4552aeda9d3d9ab7acaf84f23/phonopy/phonon/band_structure.py#L164-L178

**Comment by jochym** [comment]
I would second that but I'm not so enthusiastic about hdf5. OTOH hdf5 is already used in phonopy so no additional dependencies will be pulled in. So I second with just a small reservation. I like text-based formats - you do not need any special tools to read them.

**Comment by ExpHP** [comment]
@jochym I've tried a variety of text-based alternatives before finally switching to NPY files, and they were all still kind of slow; much faster than band.yaml for sure, but still slow.  Parsing floating point numbers is expensive.

An aside:  For a very simple alternative, python's JSON library is ***blazing fast,*** and can directly represent all of the data currently contained in the yaml.  I still don't think it scales as well as binary data once we get to structures of the size I have been working with, but it's a decent middleground.

---

To be honest I'm not a big fan of HDF5 myself, either; it feels like an ugly and bloated data format to work with.  But it is convenient for this case because **(a)** like you mentioned, the dependency is already there, and **(b)** the datasets feature does at least make for a clear way to include all of the different pieces of data in band.yaml.

**Comment by tsdev** [comment]
I was also struggling recently with importing large .yaml file outputs from Phonopy. I also support the the **hdf5** option as it is very easy to import in MATLAB.

**Comment by atztogo** [comment]
I will make --hdf5 option work for band structure mode as a material for further discussion, hopefully tomorrow.

When using hdf5, my concern is mainly in the file size. Personally I don't believe very much about the compatibility of one file made in hdf5 between different architectures. But at least in Python on x86-64 system, reading and writing hdf5 files are quite easy. I don't know other cases. Between python and fortran, I like simple binary stream.

**Comment by ExpHP** [comment]
> I will make --hdf5 option work for band structure mode as a material for further discussion, hopefully tomorrow.

Yes, it sounds good to have a starting point for discussion.

I do strongly hope in the end that it will be a separate option.  `force_constants.hdf5` is awesome, and I recommend that everybody uses it. `band.hdf5` on the other hand is something that is only necessary for BIIIIG data.  The way I picture it, anybody who wants to look at the eigenvalues or etc. will need to write a python script to extract the data they're interested in.

I'm already using lots of scripts to work with these big structures, so for me this is no big issue.  However, for many people it will be a problem.

> When using hdf5, my concern is mainly in the file size. Personally I don't believe very much about the compatibility of one file made in hdf5 between different architectures. But at least in Python on x86-64 system, reading and writing hdf5 files are quite easy.

My impression from reading about it is that HDF5 files **are** portable.  In fact, they even encode information about byte order and data size. It basically requires you to define your own data types.  (`h5py` does this automatically I think?)

A number of problems with it are described in detail here: [Cyrille Rossant - Moving away from HDF5](http://cyrille.rossant.net/moving-away-hdf5/). Many of his problems relate to modifying the files (which I don't think is something we need to do), but the biggest problem boils down to the fact that everybody is forced to use the one library that exists for reading them, written in hundreds of thousands of lines of C.

**Comment by atztogo** [comment]
> I do strongly hope in the end that it will be a separate option. 

I understand it very much to having a separate option. Within my imagination, computation of force constants from set of force files takes little time and I feel it is not necessary to read force constants from a file, but now I see it is not for all users. Increasing number of options requires some maintenance cost. This is a problem. Sometimes I ask user's patient.

At this moment using hdf5 in phono(3)py seems working. But to migrate to another file format is not a big issue, except for the documentation. I am not good at writing English, so it consumes my time. Apart from the documentation, if there is a better choice, we can move to it.

They say HDF5 files are portable. But for me, computer is not always OK though I like radiohead. I feel just lucky to see it works. If we are allowed to abandon portability (I allow), as another choice, numpy.tofile and numpy.fromfile are simple and possible for me. In this case, number of files increases, which I don't like.

> the biggest problem boils down to the fact that everybody is forced to use the one library that exists for reading them, written in hundreds of thousands of lines of C.

I agree this is a problem, but at the same time, I must thank people who work to maintain and develop it.

**Comment by atztogo** [comment]
I made 'band.hdf5' output, which is enabled by `--hdf5` option, in the 'band-hdf5' feature branch. I have not made the options like `--band-format=hdf5`.

**Comment by tsdev** [comment]
Great! Thanks, I will have a look at it soon. I hope you will use file formats that are portable, because not all Phonopy users use Python for processing the output (like me with Matlab).

**Comment by atztogo** [comment]
On the computers having similar architectures, I think Matlab works well for binary stream-IO, too. But I follow suggestions from developers and users.

**Comment by ExpHP** [comment]
Thanks for doing this. I have not had time to look at it yet (hectic day),
but when I get the chance I'll try it out and let you know what I think.

**Comment by atztogo** [comment]
It seems I merged 'band-hdf5' feature branch to the develop branch someday before. Or I may not understand the proper way of using git-rebase (I did it). Anyway, 'develop' and 'band-hdf5' are now same, so I will remove the 'band-hdf5' branch.

**Comment by ExpHP** [comment]
Uh oh. Sorry for putting this aside, I should probably look at this soon!

Having `--hdf5` control this output will break at least one piece of software that I'm working on (or force it to use `FORCE_CONSTANTS` which massively wastes disk space) so I'd rather not see this get merged yet.

**Comment by atztogo** [comment]
You don't need to rush at all.

**Comment by ExpHP** [comment]
You can try switching to `develop` and then do `git rebase -i master`; this brings up a list of all commits added since `master` and you can move things around or delete them.

Sometimes `git rebase -i` doesn't work quite the way that one might expect since it technically creates new commits (so some things work strangely, such as attempting to rebase branch C onto branch B after rebasing B onto another branch A). When all else fails, there's always the "end-all" strategy to getting a branch into the state you want, which is to do some sort of "manual rebase:"

* Let's suppose you want to manually rebase `develop` onto `master`
* `git log --oneline develop` to see a list of commits
* Create and checkout a new branch based on `master`
* Do `git cherry-pick` on each commit you want to keep
* when all is good you can use `git branch -m` to rename the branches, so that the new branch is now `develop`

**Comment by atztogo** [comment]
Thanks for the information! By --oneline, I could find I did merge 'band-hdf5' branch  at 742c42c. The detailed explanation on git-rebase will be useful for me from now.

**Comment by atztogo** [comment]
I am considering to add the following options:
--band-format
--mesh-format
--readfc-format
--writefc-format
etc
and --hdf5 will be abandoned. How do you think @ExpHP ?

**Comment by ExpHP** [comment]
that would be awesome!

What's the reasoning behind `--readfc-format` and `--writefc-format` being separate?  I think it might make more sense to have just `--fc-format` which would affect those options the way that `--hdf5` used to.

**Comment by atztogo** [comment]
To make them separate, force constants format can be converted. --fc-format can be also defined.
For option names,I plan to replace underscores by dashes :) It seems it is more usual.

By these options (--foo-format), .npy or other format will be naturally included whether I will implement it by myself or not. This is the aim.

**Comment by atztogo** [comment]
`--band-format`, `--mesh-format`, `--qpoints-format`, `--readfc-format`, and `--writefc-format` are implemented in develop branch. `--hdf5` option is still available. Now `--readfc` and `--writefc` work simultaneousl. For example, reading FORCE_CONSTANTS is possible with writing force_constants.hdf5.

In case that the other format will be supported in the future, the method in Phonopy class, `write_hdf5_band_structure` and `write_yaml_band_structure` may be better to be combined to `write_band_structure` with `format=...` keyword argument.

**Comment by ExpHP** [comment]
I've tried playing around with this, and `band.hdf5` looks great!  With this I'm now able to drop my "npy hack" branch and adopt the latest version of phonopy. Here's my immediate thoughts:

* I'm glad to see it includes the q points and distances.
* It's also nice that it is broken up by high symmetry line.
* It might be a small stumbling block for some people that the eigenvectors are actually stored columnwise (as eigenvector matrices), but it's easy enough to figure out.

(of course, I am aware that you just dumped the data in the same format that it is already stored in phonopy)

I don't think people should be too worried about the fact that it is HDF5.  It's easy enough for users to convert into another format with a short python script.  For instance, here's the script I'm using now to obtain the npy files that my codebase uses:

```python
# example: converting into npy files
import numpy as np
import h5py

band = h5py.File('band.hdf5')
np.save('eigenvector.npy', band['eigenvector'])
np.save('eigenvalue.npy', band['frequency'])
np.save('q-position.npy', band['path'])
np.save('q-distance.npy', band['distance'])
```

**Comment by atztogo** [comment]
> It's also nice that it is broken up by high symmetry line.

This is true and it should support different numbers of points along paths, but I don't know how. For eigenvectors, I think it is better so because it is straightforward in diagonalization of dynamical matrix by unitary transformation. But documentation will be necessary.

**Comment by ExpHP** [comment]
> This is true and it should support different numbers of points along paths, but I don't know how.

Hm, yeah, I doubt it will be possible to keep things this convenient when supporting different numbers of points along paths.  But it can be made **almost** as convenient.

I will share my favorite way of storing data like this, which is similar to the "compressed sparse row" format for storing sparse matrices:

---

### The format

Suppose you have `H` high symmetry lines of lengths `N[0], N[1], ..., N[H-1]` that add up to a total of `N_total` q points, and that you have `N_total` pieces of data for some variable `x` (one value at each q point).  Then you can store two things:

* **`x`:** an array of length `N_total` with all of the data.
* **`line_index`:** an array of length `H + 1` that indicates where each line begins and ends.  The first element will be 0, and the last will be `N_total`. It will look like:
  ```
  [
      0,                          # index[0]: beginning of line 0
      N[0],                       # index[1]: end of line 0, beginning of line 1
      N[0] + N[1],                # index[2]: end of line 1, beginning of line 2
      # ...                       # ...
      N[0] + N[1] + ... + N[H-1]  # index[H]: end of line H-1   (= N_total)
  ]
  ```
  This is basically `np.cumsum([0] + list(segment_nqpoint))`.

### How a typical Band.hdf5 would look

Let's say you did 101 qpoints along 3 lines on a structure with `b` bands.

For comparison, here's **the current format** of band.hdf5:

* **`frequency`**: shape `[3][101][b]`
* **`path`**: shape `[3][101][b][3]`
* **`eigenvector`**: shape `[3][101][b][b]`
* **`distance`**: shape `[3][101][b]`

And this would be **the new format:**

* **`line-index`** ` = [0, 101, 202, 303]` 
* **`frequency`**: shape `[303][b]`
* **`path`**: shape `[303][b][3]`
* **`eigenvector`**: shape `[303][b][b]`
* **`distance`**: shape `[303][b]`

### How to use the data

This format is actually a really good example of how zero-based indices and half-open ranges like python's slice syntax can be useful.  All of the most important functionality can be done without any tricky `+1`s or `-1`s (the reason for this is because `line_index` can be thought of as pointing at the spaces in-between the lines)

```python
starts = index[:-1]
ends = index[1:]

# Getting data at the `p`th point on the `h`th line
# (h is in range(H), p is in range(N[h]))
freqs = frequency[starts[h] + p]

# Getting all data for `h`th line:  (h is in range(H))
line_freqs = frequency[starts[h]:ends[h]]

# Iterating over lines:
for (start, end) in zip(starts, ends):
    line_freqs = frequency[start:end]
    # use line_freqs...
```

**Comment by ExpHP** [comment]
(in case you are reading from email, I edited the post with a graphical depiction of how to understand the format)

**Comment by ExpHP** [comment]
I've been using the feature as implemented for a while now and am pretty satisfied with it so I will close this issue
