### ISSUE TITLE
OptionParser module is deprecated

### ISSUE THREAD

**Issue by dev-zero** [atztogo/phonopy#55]
According to https://docs.python.org/2/library/optparse.html the OptionParser module is deprecated (you will also see the deprecation warning if you run pylint/flake8 or a similar linter on `phonopy_argparse.py`).
What would you like to use instead? The built-in [argparse](https://docs.python.org/2/library/argparse.html) or [Click](http://click.pocoo.org/6/)?
Given the many options I would strongly recommend the latter since it has a much more powerful interface, like verifying datatypes, checking file arguments, etc.

**Comment by jochym** [comment]
I use click myself, but it has one unfortunate problem - if your internationalization is not correctly set up it will spill out a nasty error message (with fix clearly displayed). So despite this I do recommend it - it is very powerful and easy to use.

**Comment by atztogo** [comment]
Thanks for your information. Yes we have to move to another option parser.

1) Currently I assume phonopy is still used in python 2.6. This is the reason why I don't use argparse. I will ask if I can move to python 2.7 in the phonopy mailing list.
2) Simply I didn't know about Click. I want to keep required packages to be minimum to avoid user's installation problems.

In my experience, users in scientific community read carefully documents for the usage of the code (very patient), but sometimes fail in installation even though it looks very easy for me (not patient). So even the user interface is not very elegant, it may be good for users if there are less steps for installation. But this is what I write from just my feeling.

There is another issue on current design of parsing of options in phonopy, e.g., multiple values are passed like "x y z" with quotations. It has to be considered if we will change it or not.

**Comment by dev-zero** [comment]
@atztogo I know that situation well, but Python 2.6 is not supported anymore since 4 years (2.6.9 on October 2013), so people should really upgrade (or tell their IT people to upgrade).
About the dependencies and the installation: Click is very robust, has a large user base by now (check out the extensions available for Click on pypi) and even supports Python 2.6. So, adding it to the `install_requires` in `setup.py` should be enough.

For passing multiple values: Click supports [Multi Value Options](http://click.pocoo.org/6/options/#multi-value-options) without quotations :)

**Comment by jochym** [comment]
I would vote for dropping py2.6 as well. The adoption of py3 finally started on the large scale. Personally I do not know any python library which is 2.6 only.

**Comment by atztogo** [comment]
I will abandon python 2.6 support. Thanks for your comments.
I will try Click. We will see how the internationalization problem is.

**Comment by jochym** [comment]
The internationalization is mostly small annoyance. Contact me if you get stuck with click.

**Comment by atztogo** [comment]
I wanted to follow your suggestions, but I am considering to go with argparse. The replacement of the current phonopy's optparse code by argparse seemed easier. It is just for saving my time right now, which may not be true in the long run. I totally agree, for writing new codes, Click would be a good choice.

**Comment by dev-zero** [comment]
... then wait a bit. I should do some more testing for the CP2K backend anyway plus extend the documentation in that regard and I might also take a stab at replacing the current thing with click so you can take a look.

**Comment by atztogo** [comment]
Yes, but I think we don't need to consume our time for the option parser so much. Our time should be saved for science.

**Comment by ExpHP** [comment]
Prior to 2.7, argparse was available as a regular python package, and can still be installed using e.g. `pip`.  I think that if you add "argparse" to your setup.py dependencies, then it will automatically be downloaded and be able to continue to work even on 2.6.  (not 100% sure though)

**Comment by atztogo** [comment]
I have roughly done the migration from optparse to argparse in develop branch. Now it is expected to work similarly to the case for optparse. In this chance, I work some other issues around options. The plan is:
- To replace underscores in option names by dashes
- To implement new options --band-format etc that are explained at issue #49.

Thanks @ExpHP, I didn't know it.

**Comment by atztogo** [comment]
I think this issue can be closed. Thanks for many suggestions and comments.
