### ISSUE TITLE
Request: Mode Grüneisen parameter BandStructure getters 

### ISSUE THREAD

**Issue by abelcarreras** [atztogo/phonopy#57]
Hi,

I would like to access to the band structure raw data in the Gruineisen BandStructure class:

https://github.com/atztogo/phonopy/blob/c5cd2ad57ae834c3afcf585e6374d95d21d39b7e/phonopy/gruneisen/band_structure.py#L38

which now are stored in self._path. 
I think a simple collection of getters like in phonon BandStructure class would be enough:

https://github.com/atztogo/phonopy/blob/c5cd2ad57ae834c3afcf585e6374d95d21d39b7e/phonopy/phonon/band_structure.py#L57

thanks

**Comment by atztogo** [comment]
You may think it's trivial work, but it's probably not. So I have to find some amount of time to tackle.

**Comment by atztogo** [comment]
I made a trial implementation of it in develop branch. The usage may be seen in example/Si-gruneisen/Si-gruneisen.py. If it's OK, I will make it released.

**Comment by abelcarreras** [comment]
This is exactly what I wanted. Ok for me.
Thanks
