### ISSUE TITLE
Change of default non-analytical term corretion

### ISSUE THREAD

**Issue by atztogo** [atztogo/phonopy#64]
I am planning to change the default non-analytical term correction method from the current one (Wang et al) to the other one (Gonze et al). The later can be used with --nac-method='gonze' at the latest versions.

To release it as the default NAC, what kind of message should I show?

**Comment by sauluck** [comment]
I feel you should have both options available
--nac -wang
--nac -gonze

**Comment by atztogo** [comment]
This can be done by `--nac-method='wang'` or `--nac-method='gonze'`. Currently the default is the former.

**Comment by atztogo** [comment]
At v1.13.0, the method by Gonze et al. is made as the default method.
