### ISSUE TITLE
get_positions_sent_by_rot_inv is occasionally given inputs that fail to be symmetric (beyond numerical error)

### ISSUE THREAD

**Issue by ExpHP** [atztogo/phonopy#65]
Provided is a test case that causes the current version of phonopy to fail.

[phonopy-rot-inv-error.tar.gz](https://github.com/atztogo/phonopy/files/1907919/phonopy-rot-inv-error.tar.gz)

```
$ phonopy --tolerance 2e-2 band.conf --fc-format=hdf5 --band-format=hdf5 --writefc
        _
  _ __ | |__   ___  _ __   ___   _ __  _   _
 | '_ \| '_ \ / _ \| '_ \ / _ \ | '_ \| | | |
 | |_) | | | | (_) | | | | (_) || |_) | |_| |
 | .__/|_| |_|\___/|_| |_|\___(_) .__/ \__, |
 |_|                            |_|    |___/
                                      1.12.8

Warning: Force constants are not prepared.
Python version 3.6.4
Spglib version 1.10.3
Band structure mode
Settings:
  Supercell: [1 1 8]
Spacegroup: Pm (6)
Computing force constants...
Encounter some problem in compute_permutation.
Traceback (most recent call last):
  File "/home/lampam/.local/bin/phonopy", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/lampam/asd/clone/phonopy/scripts/phonopy", line 661, in <module>
    computation_algorithm=settings.get_fc_computation_algorithm())
  File "/home/lampam/asd/clone/phonopy/phonopy/api_phonopy.py", line 377, in produce_force_constants
    computation_algorithm=computation_algorithm)
  File "/home/lampam/asd/clone/phonopy/phonopy/api_phonopy.py", line 1320, in _run_force_constants_from_forces
    computation_algorithm=computation_algorithm)
  File "/home/lampam/asd/clone/phonopy/phonopy/harmonic/force_constants.py", line 87, in get_fc2
    computation_algorithm=computation_algorithm)
  File "/home/lampam/asd/clone/phonopy/phonopy/harmonic/force_constants.py", line 716, in _get_force_constants_disps
    computation_algorithm=computation_algorithm)
  File "/home/lampam/asd/clone/phonopy/phonopy/harmonic/force_constants.py", line 268, in solve_force_constants
    symprec)
  File "/home/lampam/asd/clone/phonopy/phonopy/harmonic/force_constants.py", line 591, in _solve_force_constants_svd
    symprec)
  File "/home/lampam/asd/clone/phonopy/phonopy/harmonic/force_constants.py", line 282, in get_positions_sent_by_rot_inv
    symprec)
  File "/home/lampam/asd/clone/phonopy/phonopy/harmonic/force_constants.py", line 865, in _compute_permutation_for_rotation
    symprec)
  File "/home/lampam/asd/clone/phonopy/phonopy/harmonic/force_constants.py", line 901, in _compute_permutation_c
    permutation_error()
  File "/home/lampam/asd/clone/phonopy/phonopy/harmonic/force_constants.py", line 889, in permutation_error
    raise ValueError("Input forces are not enough to calculate force constants, "
ValueError: Input forces are not enough to calculate force constants, or something wrong (e.g. crystal structure does not match).
```

## Investigation

When it fails, it mentions the `compute_permutation` function that I added.  Furthermore, when I try running a version of phonopy prior to that change (21cb9e37240df3d8e7217c428370819424e6eead), the crash does not occur, and there are no error messages.

Since it appeared that this might be due to a bug in my contributions, I continued to look further into it.

### What makes it fail?

To help answer this question, I added debug output to the `compute_permutation` C function to make it print the best distance it found whenever it failed to find any distances less than `symprec`.

* **All of the distances it printed were approximately equal to `0.025 A`, which is quite a bit bigger than `symprec=0.02 A`!** (so this isn't just numerical error)
* I printed out the structures for `positions` and `rot_pos` in `get_positions_sent_by_rot_inv`, and these are included in the archive.  Indeed, **some atoms really do move by a distance of 0.025A between the two files.**

This suggests something is wrong with the input to the function or how it is used, but looking further into it, I found to my surprise that `get_positions_sent_by_rot_inv` receives exactly the same input in both the new and old versions.

### Why didn't the old version fail?

As it turns out, **the bug already existed.  It's just that old versions of phonopy didn't notice that anything was wrong.**  The reason it wasn't detected is thanks to these lines in the old version:

```python
j = np.nonzero(np.sqrt(np.sum(diff ** 2, axis=1)) < symprec)[0]
rot_map[j] = i
```

Deceptively, it looks like this should detect when there are no overlapping positions (by failing with an IndexError), but in fact it succeeds because *np.nonzero actually returns a tuple.*

So what used to happen when none of the positions were closer than symprec is that `j` would be an empty array, and `rot_map[np.array([])] = i` did nothing.  In the end, there would be a bunch of extra `0`s leftover in `rot_map`.

## Files

Here's the link again: [phonopy-rot-inv-error.tar.gz](https://github.com/atztogo/phonopy/files/1907919/phonopy-rot-inv-error.tar.gz) (12.4MB)

- **`run`**: script to run phonopy with the right arguments
- **`band.conf`, `FORCE_SETS`, `POSCAR`:** Input files
- **`pos.vasp`, `rot.vasp`:** Structures showing `positions` and `rot_pos` received by `get_positions_sent_by_rot_inv` when it fails.

**Comment by atztogo** [comment]
Thanks. I will have a look.

The symprec=0.02 is too large for phonopy with respect to my expectation. So I may loosely write code not to adapt it. It is recommended to make your structure be symmetrized before starting.

**Comment by ExpHP** [comment]
The test case purposefully used a large symprec to make it easier to trigger the error.  It does happen with smaller symprecs, but the structures where I've run into trouble with it were too large for easy debugging.

**Comment by atztogo** [comment]
There is inconsistency between spglib and phonopy symmetry handlings. In symmetry finding, spglib works to make the symmetry operations form a space group by adjusting symmetry tolerance internally to suggest at least one any space group type. Phonopy just uses symmetry operations given by spglib. Using this symmetry operations with the fixed tolerance, inconsistency can happen.

Instead of this,
```np.nonzero(np.sqrt(np.sum(diff ** 2, axis=1)) < symprec)```
searching shortest one may work
```permutation[i] = [np.argmin(np.sqrt(np.sum(diffs**2, axis=1)))]```
though dangerous. This change does not affect wrongly to the phonopy examples. But your force constants are calculated badly. This is probably creating displacements was not consistent with this change, but just recreating displacements and calculating forces would not work anyway, I guess.

I think there is no perfect solution as long as an input structure has distortion against symmetrically ideal structure. If the distortion is of the size of symmetry tolerance, the current algorithm is unstable. How should we treat it? One practical solution is to ask users to symmetrized input crystal structure before starting phonon calculation but by the symmetrization, the input cell is transformed to a standardized setting, where rigid rotation, translation, change of cell size can happen. To do symmetraization internally without telling to users is another option. But
 for which I will need some more implementation in spglib or phonopy, to avoid those rotation, translation, and change of cell size, which is not a trivial task. In this case, the direction is implementing [this](https://sourceforge.net/p/spglib/mailman/spglib-users/thread/D0A79931-6AFE-40BB-B910-A436B61A316C%40nrl.navy.mil/#msg36164080).

**Comment by ExpHP** [comment]
> `permutation[i] = [np.argmin(np.sqrt(np.sum(diffs**2, axis=1)))]`

Perhaps not this since that line is from the old version, but something similar can be done in the C code.  (record the objective used for sorting as a cartesian distance, stop searching when that objective has increased by a difference of `2*symprec` and use the best position found)

**Comment by atztogo** [comment]
Quality of force constants should be better if forces are calculated symmetrized crystal structure. If forces are calculated for distorted structures, the quality of force constants is not secured by symmetrization. Another point is how we can measure the quality of force constants. This depends on purposes, too. However we are very interested in it. For example, The software [Alamode](http://alamode.readthedocs.io/en/latest/index.html), [hiPhive](https://hiphive.materialsmodeling.org/), [TDEP](http://ollehellman.github.io/) are working for it for similar and different purposes 

A difficulty of symmetrization is how users wanto to symmetrize their structures. In spglib, I use crystallographic convention to do it, by which their input structures may be rotated, translated and their unit cell sizes can be changed. Probably users are not happy if their structures are largely modified by the looks. Then I have to implement the symmetrization procedure to minimize the lattice and atomic position modification but their shapes and sites are ideal.

To write out symmetrized structure, ``disp.yaml`` is quite OK and can keep before and after symmetrization. I don't want to create many files automatically, so symmetrized POSCAR-format file may be created by user's will like --symmetry option. But this case, I have to support non-VASP interfaces.

**Comment by atztogo** [comment]
I add some comment on this old issue of symmetrization. It is possible to symmetrize crystal structure but that is to be resembling to the input structure. It was discussed on this in spglib mailing list.

https://sourceforge.net/p/spglib/mailman/spglib-users/thread/D0A79931-6AFE-40BB-B910-A436B61A316C%40nrl.navy.mil

For which, using the idea to use SVD is a good idea and implementation in python is easy,

https://sourceforge.net/p/spglib/mailman/message/36164080/

**Comment by atztogo** [comment]
We don't have discussion for long time.

I think your implementation is quite OK. Just the symmetry tolerance is a difficult parameter.  I inserted an interation loop to increase the tolerance little by little until match. See 61f29b8a if you are interested in it.

 I am going to close this issue. If you have still interest in this, please re-open this.
