### ISSUE TITLE
A possible “bug” in dealing with unit cell

### ISSUE THREAD

**Issue by devecrytiantian** [atztogo/phonopy#68]
Hi！
    When I was using phononpy program to process phonon spectrum, I found a possible "bug". There were only three quite small imaginary frequencies in calculations of VASP, which could be ignored as shown below:

 142 f/i=    0.004774 THz     0.029999 2PiTHz    0.159259 cm-1     0.019746 meV
 143 f/i=    0.018306 THz     0.115023 2PiTHz    0.610638 cm-1     0.075709 meV
 144 f/i=    0.018306 THz     0.115023 2PiTHz    0.610638 cm-1     0.075709 meV

However, unfortunately, I found that a series of imaginary frequencies appeared in hgh symmetric point path of brillouin zone as displayed in figure.
![1](https://user-images.githubusercontent.com/39618231/40542791-1e201736-6011-11e8-86c2-93952cbdec47.jpg)

Due to limitation of computing resource, I cannot adopt a big supercell to recaculate the phonon. The crystal constants of unit cell of my calculations are near 8 A, 8 A, 27 A, respectively.  After that, I have done some test in some small systems where the similar cases happened but vanished in a supercell.

Therefore, I would like to know why this happened?

**Comment by atztogo** [comment]
I think it is not the matter of the bug of the code. So please send your question to the phonopy mailing list. So I will close this issue.
