### ISSUE TITLE
Siesta reading discards LatticeVector units for non-Bohr unit

### ISSUE THREAD

**Issue by zerothi** [atztogo/phonopy#71]
When using phonopy to create the displacement table for Siesta I find that it only corrects the positions depending on the LatticeConstant, and not the LatticeVectors.

I.e. when it writes out the supercell afterwards the fractional coordinates are *correct* while the supercell becomes too small.

Thanks for this great software!

**Comment by atztogo** [comment]
Siesta interface was developed by @henriquemiranda. Henrique, do you have any idea?

**Comment by henriquemiranda** [comment]
Indeed the Siesta input file has many options, it might be that I overlooked something.
Perhaps I did not include an example input file with this variable in the tests.
@zerothi Could you share an example input file reproducing the problem?
We can modify the interface to handle that case.

**Comment by atztogo** [comment]
Thanks. If you want to change/create other files than siesta.py, for example need to write unittest, please let me know.

**Comment by zerothi** [comment]
Dear @atztogo and @henriquemiranda 

I have found the bug.

The errors come up with these files:

`Ang.fdf`:
```bash
LatticeConstant 1. Ang
%block LatticeVectors
 1.00000000 0.00000000 0.00000000
 0.00000000 10.00000000 0.00000000
 0.00000000 0.00000000 10.00000000
%endblock LatticeVectors

NumberOfAtoms 1
AtomicCoordinatesFormat Ang
%block AtomicCoordinatesAndAtomicSpecies
 0.50000000 0.50000000 0.50000000 1 # 1
%endblock AtomicCoordinatesAndAtomicSpecies
```

`Bohr.fdf`
```bash
LatticeConstant 1. Bohr
%block LatticeVectors
 1.88972688 0.00000000 0.00000000
 0.00000000 18.89726878 0.00000000
 0.00000000 0.00000000 18.89726878
%endblock LatticeVectors

NumberOfAtoms 1
AtomicCoordinatesFormat Bohr
%block AtomicCoordinatesAndAtomicSpecies
 0.94486344 0.94486344 0.94486344 1 # 1
%endblock AtomicCoordinatesAndAtomicSpecies
```


`Fractional.fdf`:
LatticeConstant 1. Ang
%block LatticeVectors
 1.00000000 0.00000000 0.00000000
 0.00000000 10.00000000 0.00000000
 0.00000000 0.00000000 10.00000000
%endblock LatticeVectors

NumberOfAtoms 1
AtomicCoordinatesFormat Fractional
%block AtomicCoordinatesAndAtomicSpecies
 0.50000000 0.05000000 0.05000000 1 # 1
%endblock AtomicCoordinatesAndAtomicSpecies
```

in which case only `Bohr.fdf` produces the correct `supercell.fdf`.
They were converted using:

    phonopy --siesta -d --dim="2 1 1" -c ../<>.fdf

and each checked.

I have a fix that I will submit. But perhaps you may want to add these as tests?

**Comment by atztogo** [comment]
Thanks. If @henriquemiranda is OK, I will merge @zerothi 's pull request.

**Comment by atztogo** [comment]
Maybe it is easier for us to review by making a branch in repository. So I attempted at merging @zerothi 's pull request at
https://github.com/atztogo/phonopy/tree/zerothi-siesta
In case that you think this is convenient, please use it.

**Comment by zerothi** [comment]
Well, to me it does not make a difference.. ;)
It is quite easy to have several different remotes on the same git dev repo. But if you want to test it in your repo, feel free to do so. :)

**Comment by atztogo** [comment]
You are correct!

**Comment by henriquemiranda** [comment]
Hi, the correction seems fine to me.
I just think it would be a good idea to add a test using this new input files to make sure the interface does not break with some future change.
I noticed that my old tests are in the examples folder and are run with shell scripts.
Maybe it's a good idea to put them in a new unit test script in:
test/phonopy/interface/test_siesta.py
I cannot promise to do that immediately.

**Comment by atztogo** [comment]
OK. I merged @zerothi's pull request to ``develop`` branch. For the test, if you could write, you can find those for other interfaces at ``test/phonopy/interface``. I removed ``zerothi-siesta`` branch.
