### ISSUE TITLE
--band-format=hdf5 does not have any effect in 1.13.2 (BAND_FORMAT in conf still works)

### ISSUE THREAD

**Issue by ExpHP** [atztogo/phonopy#75]
When I specify `--band-format=hdf5` on 1.13.2, it still creates band.yaml instead of band.hdf5.

* 1.13.0 worked fine
* `BAND_FORMAT = hdf5` in a conf file works fine

I looked through the commit list between 1.13.0 and 1.13.2 for changes related to arguments.  Could it have been this commit that broke it?: https://github.com/atztogo/phonopy/commit/2c5717c2b84919738c788d5967ad441d5e15e886

**Comment by ExpHP** [comment]
Ah, I see from the comments in #73 that you were afraid something might happen.

Maybe I can help clean up (or perhaps rewrite) the settings code at some point.  Personally there's some things I would like to see (like support for multiple `conf` files) that could be made possible by having a simpler configuration model.

**Comment by atztogo** [comment]
I try to fix it, though it would be like an ad-hoc fix.
It must be pity for me that you lose your time for this parser improvement.

**Comment by ExpHP** [comment]
I tried the new commit and it looks like it is working, thanks!

> It must be pity for me that you lose your time for this parser improvement.

Don't worry; after I noticed it I just switched to v1.13.0, so not much time was lost. :slightly_smiling_face:

**Comment by atztogo** [comment]
I will close this issue :-)
