### ISSUE TITLE
Phonopy 1.13.2.107 release tag

### ISSUE THREAD

**Issue by davidhrbac** [atztogo/phonopy#78]
There is no release 1.13.2.107 at https://github.com/atztogo/phonopy/releases. But I can see Phonopy 1.13.2.107 at https://pypi.org/project/phonopy/#history. Can you push the release to GH?

**Comment by atztogo** [comment]
The latest PyPI phonopy version corresponds to the master branch on github.

**Comment by davidhrbac** [comment]
We rely on the release tag to install the software, not on the master...

**Comment by atztogo** [comment]
For which purpose?

**Comment by davidhrbac** [comment]
We install Phonopy on our clusters, we need the release tag to tag the module...

**Comment by atztogo** [comment]
If you can get the version number like 1.13.2.107, it is fine? I mean I don't want to make git tag for each small version, but the number can be generated by the command `git`.

**Comment by davidhrbac** [comment]
Yes, the point is that proper tag is the must for the deployment. It does not make sense to have release on PiPy without having release tag on repository. How could you compare this release when you add a single commit to master?!?
Anyway, update services, like Debian or Fedora are using release tag to get update info. So, this release is not going to be picked up by the distros. We will do so, we will not deliver Phonopy to our user from master.

**Comment by atztogo** [comment]
You are correct. I think only following github releases is fine. Maybe I do the same for PyPI.

**Comment by atztogo** [comment]
Now I start to be more careful in versioning based on semantic versioning (as recommended by @merkys in spglib). I think you can trust better the github releases than before.

**Comment by davidhrbac** [comment]
Thanks, closing the ticket.
