### ISSUE TITLE
irreps analysis with the NAC option

### ISSUE THREAD

**Issue by pastle** [atztogo/phonopy#82]
Dear Dr. Togo

I'm using phonopy together with abinit to calculate phonon dispersions. However, there seem to be two problems.
1. With the --nac option, the mesh and band calculations produce quite different phonon frequencies at the gamma point. Can I know why are they different?
2. The gamma-point phonon frequencies in the irreps analysis output file is not changing with the the --nac option and always stay with the zero Born effective charge values. Then how to analyze the raman/infrared activity once the --nac option is included?
Thanks a lot for your help!

Wishes
Shang

**Comment by atztogo** [comment]
You can use `--nac` and `--q-direction` simultaneously to break symmetry at Gamma.

**Comment by atztogo** [comment]
I will close this issue.

**Comment by weixie4** [comment]
Dear Professor Togo,

Can I ask a question related to this issue? By including --nac and --q-direction command line options as you suggested above, I did indeed manage to get LO-TO splitting in both band.yaml and irreps.yaml files, but in mesh.yaml, for each irreducible representation, the LO mode is still degenerate with the two TO modes at gamma point. I think this leads to incorrect projected density of states. Can you please let me know how I can handle this issue? 

Many thanks,
Wei

**Comment by atztogo** [comment]
It is the effect at non-zero q-point but at limit of q->0. So I have no idea how to include at Gamma point for mesh case as implementation.
