### ISSUE TITLE
phonopy -f vasprun.xml error

### ISSUE THREAD

**Issue by protik77** [atztogo/phonopy#9]
I am trying to install phonopy in a CentOS machine. I have installed all the libraries needed. The isntallation worked fine. Now every example is working except the Si example. While trying "./phonopy -f vasprun.xml", I'm getting this:

```
counter (file index): Python 2.5 or later is needed.
For creating FORCE_SETS file with Python 2.4, you can use phonopy 1.8.5.1 with python-lxml .
```
My python -V shows:
```
Python 2.6.6
```

**Comment by atztogo** [comment]
Could you send your question to the mailing list?
https://lists.sourceforge.net/lists/listinfo/phonopy-users
