### ISSUE TITLE
Creating displacements with the quiet option does not write a phonopy_disp.yaml

### ISSUE THREAD

**Issue by bocklund** [atztogo/phonopy#99]
Given any POSCAR (reproduced with the following):

```
Al1
1.0
2.473329 0.000000 1.427977
0.824443 2.331877 1.427977
0.000000 0.000000 2.855955
Al
1
direct
0.000000 0.000000 0.000000 Al
```

Running `phonopy -q -d --dim='3 3 3'` does not create a `phonopy_disp.yaml` (it still correctly creates the SPOSCAR and POSCAR-001 that I would expect). Running `phonopy -d --dim='3 3 3'` gives me the expected POSCARs and the expected `phonopy_disp.yaml`.

I am using `phonopy==2.2.0` on Python 3.7

**Comment by atztogo** [comment]
Thanks. I fixed it at https://github.com/atztogo/phonopy/commit/edce334c3b2550d1fd05dc7b7c12ed8535a8c57b, currently in develop branch.

**Comment by bocklund** [comment]
Ah, okay! Thanks!
